version: "3.5"
services:
    backend:
        build: ./backend
        restart: always
        volumes:
            - ./backend/app:/opt/app
            - ./backend/migrations:/opt/migrations
        environment:
            - DB_URL=mysql+pymysql://root:homework@db/homework
            - WORKERS=1

    db:
        image: mariadb:10.4
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=homework
            - MYSQL_DATABASE=homework
        volumes:
            - .data/mysql:/var/lib/mysql
        # This command is required to set important mariadb defaults
        command:
            [
                mysqld,
                --character-set-server=utf8mb4,
                --collation-server=utf8mb4_unicode_ci,
                --wait_timeout=28800,
                --log-warnings=0,
            ]
    adminer:
        image: adminer
        ports:
            - 8080:8080

    frontend:
        build: ./frontend
        ports:
            - 80:80
        volumes:
            - ./logs:/var/log/nginx
